apiVersion: v1
kind: Service
metadata:
  labels:
    app: tenant-kubernetes
    role: apiserver
  name: tenant-kubernetes
spec:
  ports:
  - name: tenant-kubernetes-apiserver
    port: 6443
    protocol: TCP
    targetPort: 6443
  selector:
    app: tenant-kubernetes
    role: apiserver
  type: ClusterIP
